version: '3.9'
services:
  postgres:
    image: isac:1.0
    build:
      context: ./database
    container_name: 'isac'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DATABASE
